# All paths are relative to this file.

# Paths.
# place the search right next to this file
output_path: './'

# Providers from which to search (case insensitive)
providers:
  - 'Indeed'
  - 'Monster'
  - 'GlassDoor' # This used to take ~10x longer to run than the other providers
   

# Filters.
search_terms:
  region:
    province: 'Punjab'
    city:     'Lahore'
    domain:   'com'
    radius:   10

  keywords:
    - 'Frontend'
    #- 'React'
    #- 'Reactjs'
    #- 'React Native'
    #- 'React JS'
    #- 'Senior Frontend'

black_list:
  - 'some black list company'
  - 'other company'

# Logging level options are: critical, error, warning, info, debug, notset
log_level: 'info'

# Saves duplicates removed by tfidf filter to duplicate_list.csv
save_duplicates: False

# Turn on or off delaying
set_delay: False

# Delaying algorithm configuration
delay_config:
    # Functions used for delaying algorithm, options are: constant, linear, sigmoid
    function: 'linear'
    # Maximum delay/upper bound for converging random delay
    delay: 30
    # Minimum delay/lower bound for random delay  
    min_delay: 15 
    # Random delay
    random: True 
    # Converging random delay, only used if 'random' is set to True
    converge: True 
    
    