# Generated by Django 2.2.3 on 2019-07-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Page',
            new_name='Pages',
        ),
    ]
